In [2]:
import numpy as np

In [5]:
n = 10
a = np.arange(0,n)
for i in a:
    a[i] = n- i -1
print(a)

[9 8 7 6 5 4 3 2 1 0]


In [8]:
n = 7
a = np.eye(n)
sum_diag = 0
i = 0
while i < n:
    a[i,i] = n- i -1
    sum_diag += a[i,i] 
    i += 1
print(a,'\n','sum_diag = ',sum_diag )

[[6. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 
 sum_diag =  21.0


In [9]:
from numpy import linalg
a = np.array([[4,2,1], [1,3,0],[0,5,4]])
b = np.array([4,12,-3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

resalt = []
i = 0
while i < len(users_stats):
    cos =  cosine(users_stats[i],next_user_stats )
    resalt.append(cos)
    i += 1
print(resalt)
min_res = min(resalt)
i = 0
print('Самые похожие пользователи:')
while i < len(resalt):
    if resalt[i] == min_res:
        print(i+1,' ',users_stats[i]  )
    i +=1

[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]
Самые похожие пользователи:
6   [0 0 0 0 0 5]
7   [1 0 0 0 0 0]
9   [0 0 0 1 1 3]
10   [1 0 0 2 1 4]
